---
- name: Harden SSH configuration (ALT 8)
  ansible.builtin.blockinfile:
    path: /etc/ssh/sshd_config
    block: |
      Ciphers aes256-ctr,aes192-ctr,aes128-ctr
      MACs hmac-sha2-512-etm@openssh.com,hmac-sha2-256-etm@openssh.com
      PermitRootLogin no
    marker: "# {mark} secaudit"
  notify: restart sshd

- name: Set iptables default policy to DROP
  ansible.builtin.blockinfile:
    path: /etc/sysconfig/iptables
    block: |
      *filter
      :INPUT DROP [0:0]
      :FORWARD DROP [0:0]
      :OUTPUT ACCEPT [0:0]
      -A INPUT -i lo -j ACCEPT
      -A INPUT -m state --state ESTABLISHED,RELATED -j ACCEPT
      -A INPUT -p tcp -m tcp --dport 22 -j ACCEPT
      -A INPUT -p tcp -m tcp --dport 9100 -j ACCEPT
      COMMIT
    create: yes
  notify: restart iptables

- name: Ensure /etc/shadow permissions are strict
  ansible.builtin.file:
    path: /etc/shadow
    owner: root
    group: root
    mode: "0000"

- name: Configure auditd log rotation (ALT 8)
  ansible.builtin.lineinfile:
    path: /etc/audit/auditd.conf
    regexp: '^max_log_file'
    line: 'max_log_file = {{ (secaudit_target_environment == "prod") | ternary(20, 50) }}'
  notify: restart auditd

- name: Enable aide integrity timer
  ansible.builtin.service:
    name: aidecheck.timer
    state: started
    enabled: yes
  notify: restart aide timer
