---
- name: Disable SSH root login (Astra Linux)
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^PermitRootLogin'
    line: 'PermitRootLogin no'
  notify: restart sshd

- name: Deploy auditd rules for confidential files
  ansible.builtin.copy:
    dest: /etc/audit/rules.d/hardening.rules
    content: |
      -w /etc/shadow -p wa -k confidential
      -w /etc/gshadow -p wa -k confidential
    owner: root
    group: root
    mode: "0640"
  notify:
    - restart auditd

- name: Configure unattended upgrades
  ansible.builtin.copy:
    dest: /etc/apt/apt.conf.d/20auto-upgrades
    content: |
      APT::Periodic::Update-Package-Lists "1";
      APT::Periodic::Unattended-Upgrade "1";
    owner: root
    group: root
    mode: "0644"

- name: Protect sudo with pam_tally2
  ansible.builtin.lineinfile:
    path: /etc/pam.d/sudo
    insertafter: '^auth'
    regexp: 'pam_tally2'
    line: 'auth required pam_tally2.so deny={{ (secaudit_target_environment == "prod") | ternary(5, 8) }} even_deny_root unlock_time=300'

- name: Ensure osquery package installed
  ansible.builtin.package:
    name: osquery
    state: present
  notify: restart osqueryd
