---
- name: Add Wazuh repository key (Debian)
  ansible.builtin.get_url:
    url: https://packages.wazuh.com/key/GPG-KEY-WAZUH
    dest: /usr/share/keyrings/wazuh.asc
    mode: "0644"
  when: ansible_facts['os_family'] == 'Debian'

- name: Configure Wazuh repository (Debian)
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64 signed-by=/usr/share/keyrings/wazuh.asc] https://packages.wazuh.com/4.x/apt stable main"
    filename: wazuh
    state: present
  when: ansible_facts['os_family'] == 'Debian'

- name: Configure Wazuh repository (RedHat)
  ansible.builtin.yum_repository:
    name: wazuh
    description: Wazuh repository
    baseurl: https://packages.wazuh.com/4.x/yum/
    gpgcheck: yes
    gpgkey: https://packages.wazuh.com/key/GPG-KEY-WAZUH
  when: ansible_facts['os_family'] == 'RedHat'

- name: Install wazuh-agent package
  ansible.builtin.package:
    name: wazuh-agent
    state: present

- name: Configure wazuh-agent
  ansible.builtin.template:
    src: ossec.conf.j2
    dest: /var/ossec/etc/ossec.conf
    owner: root
    group: ossec
    mode: "0640"

- name: Register agent with manager
  ansible.builtin.command: >
    /var/ossec/bin/agent-auth -m {{ wazuh_manager_address }} -P {{ wazuh_registration_password }} -G {{ wazuh_agent_groups | join(',') }}
  args:
    creates: /var/ossec/etc/client.keys
  notify: restart wazuh-agent

- name: Ensure wazuh-agent service is enabled and started
  ansible.builtin.service:
    name: wazuh-agent
    state: started
    enabled: true
