osquery_version: 5.11.0
osquery_additional_flags:
  - "--disable_events=false"
  - "--logger_path=/var/log/osquery"
  - "--logger_plugin=filesystem,syslog"
  - "--config_plugin=filesystem"
osquery_packs:
  - inventory
  - vulnerability-management
osquery_tls_hostname: kuma-collector.example.com
telegraf_outputs:
  - type: http
    url: https://kuma-gateway.example.com/collect
    headers:
      Authorization: "Bearer change-me"
    insecure_skip_verify: false
  - type: influxdb_v2
    urls:
      - https://influx.example.com
    token: "influx-token"
    organization: security
    bucket: osquery
