# Dockerfile.wazuh-indexer
FROM wazuh/wazuh-indexer:4.13.1

USER root

COPY config/wazuh-indexer/certs/ /etc/wazuh-indexer/certs/

# Жёстко правим права, чтобы OpenSearch Security смог читать root-ca.pem
RUN chown -R 1000:1000 /etc/wazuh-indexer/certs/ && \
    chmod 644 /etc/wazuh-indexer/certs/*.pem && \
    chmod 600 /etc/wazuh-indexer/certs/*.key && \
    ls -la /etc/wazuh-indexer/certs/

USER 1000
