---
- name: restart sshd
  ansible.builtin.service:
    name: "{{ 'sshd' if ansible_facts['os_family'] == 'RedHat' else 'ssh' }}"
    state: restarted

- name: restart auditd
  ansible.builtin.service:
    name: auditd
    state: restarted
  when: ansible_facts['os_family'] == 'RedHat'
