apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    url: http://172.18.0.1:9090
    access: proxy
    isDefault: true
    editable: true
    jsonData:
      timeInterval: "15s"
      httpMethod: "POST"
