---
- name: Enforce password policy
  ansible.windows.win_password_policy:
    complexity: "{{ windows_password_policy.complexity }}"
    minimum_password_length: "{{ windows_password_policy.minimum_length }}"
    maximum_password_age: "{{ windows_password_policy.maximum_age_days }}"
    password_history_size: "{{ windows_password_policy.history_size }}"

- name: Configure account lockout policy
  ansible.windows.win_security_policy:
    section: System Access
    key: LockoutBadCount
    value: 5

- name: Enable firewall profiles
  ansible.windows.win_firewall_profile:
    name: "{{ item }}"
    state: enabled
    allow_inbound_rules: false
    allow_local_firewall_rules: true
    allow_local_ipsec_rules: true
  loop: "{{ windows_firewall_profiles }}"

- name: Configure auditing policies
  ansible.windows.win_audit_policy_system:
    subcategory: "{{ item.subcategory }}"
    audit_type: "{{ item.setting }}"
  loop: "{{ windows_audit_policies }}"

- name: Disable insecure SMBv1 protocol
  ansible.windows.win_feature:
    name: FS-SMB1
    state: absent

- name: Ensure PowerShell transcription is enabled
  ansible.windows.win_regedit:
    path: HKLM:\SOFTWARE\Policies\Microsoft\Windows\PowerShell\Transcription
    name: EnableTranscripting
    data: 1
    type: dword

- name: Enable PowerShell module logging
  ansible.windows.win_regedit:
    path: HKLM:\SOFTWARE\Policies\Microsoft\Windows\PowerShell\ModuleLogging
    name: EnableModuleLogging
    data: 1
    type: dword

- name: Configure PowerShell script block logging
  ansible.windows.win_regedit:
    path: HKLM:\SOFTWARE\Policies\Microsoft\Windows\PowerShell\ScriptBlockLogging
    name: EnableScriptBlockLogging
    data: 1
    type: dword
