version: "3.9"
services:
  wazuh-indexer:
    image: wazuh/wazuh-indexer:4.13.1
    hostname: wazuh-indexer
    restart: unless-stopped
    environment:
      - DISABLE_SECURITY_PLUGIN=false
      - OPENSEARCH_JAVA_OPTS=-Xms1g -Xmx1g
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=${WAZUH_INDEXER_PASSWORD:-SecretPassword123!}
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    ports:
      - "9200:9200"
    volumes:
      - wazuh-indexer-data:/var/lib/wazuh-indexer
      - ./config/indexer/opensearch.yml:/usr/share/wazuh-indexer/config/opensearch.yml:ro

  wazuh-manager:
    image: wazuh/wazuh-manager:4.13.1
    hostname: wazuh-manager
    restart: unless-stopped
    depends_on:
      - wazuh-indexer
    environment:
      - WAZUH_INDEXER_URL=https://wazuh-indexer:9200
      - WAZUH_INDEXER_USER=admin
      - WAZUH_INDEXER_PASSWORD=${WAZUH_INDEXER_PASSWORD:-SecretPassword123!}
      - WAZUH_API_USER=admin
      - WAZUH_API_PASSWORD=${WAZUH_API_PASSWORD:-AnotherSecretPassword456!}
    ports:
      - "1514:1514/udp"
      - "1515:1515"
      - "55000:55000"
    volumes:
      - wazuh-manager-data:/var/ossec/data
      - ./config/manager/ossec.conf:/var/ossec/etc/ossec.conf:ro
      - ./config/manager/api:/var/ossec/api/configuration:ro

  wazuh-dashboard:
    image: wazuh/wazuh-dashboard:4.13.1
    hostname: wazuh-dashboard
    restart: unless-stopped
    depends_on:
      - wazuh-manager
      - wazuh-indexer
    environment:
      - OPENSEARCH_HOSTS=["https://wazuh-indexer:9200"]
      - OPENSEARCH_USERNAME=admin
      - OPENSEARCH_PASSWORD=${WAZUH_INDEXER_PASSWORD:-SecretPassword123!}
      - OPENSEARCH_DASHBOARDS_USERNAME=admin
      - OPENSEARCH_DASHBOARDS_PASSWORD=${WAZUH_API_PASSWORD:-AnotherSecretPassword456!}
    ports:
      - "5601:5601"
    volumes:
      - ./config/dashboard/opensearch_dashboards.yml:/usr/share/wazuh-dashboard/config/opensearch_dashboards.yml:ro

volumes:
  wazuh-indexer-data:
  wazuh-manager-data:
