version: "3.9"
services:
  wazuh-indexer:
    image: wazuh/wazuh-indexer:4.7.2
    hostname: wazuh-indexer
    restart: unless-stopped
    environment:
      - bootstrap.password=changeme
      - discovery.type=single-node
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    ports:
      - "9200:9200"
    volumes:
      - wazuh-indexer-data:/var/lib/wazuh-indexer

  wazuh-manager:
    image: wazuh/wazuh-manager:4.7.2
    hostname: wazuh-manager
    restart: unless-stopped
    depends_on:
      - wazuh-indexer
    ports:
      - "1514:1514/udp"
      - "1515:1515"
      - "55000:55000"
    volumes:
      - wazuh-manager-data:/var/ossec/data
      - ./config/manager/ossec.conf:/var/ossec/etc/ossec.conf:ro

  wazuh-dashboard:
    image: wazuh/wazuh-dashboard:4.7.2
    hostname: wazuh-dashboard
    restart: unless-stopped
    depends_on:
      - wazuh-manager
      - wazuh-indexer
    environment:
      - DASHBOARD_USERNAME=admin
      - DASHBOARD_PASSWORD=changeme
      - WAZUH_API_URL=https://wazuh-manager:55000
      - WAZUH_API_USER=wazuh-wui
      - WAZUH_API_PASSWORD=SecretPassword
    ports:
      - "5601:5601"

volumes:
  wazuh-indexer-data:
  wazuh-manager-data:
